version: '3.3'

services:

  api:
    build:
      context: api
    container_name: woaq-api
    image: openoakland/woaq-api

  web:
    build:
      context: web
    container_name: woaq-web
    image: openoakland/woaq-web

  db:
    container_name: woaq-db
    image: mdillon/postgis:11

  proxy:
    build:
      context: nginx-proxy
    container_name: woaq-proxy
    image: openoakland/woaq-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
